name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: composer install --ansi --no-progress --no-interaction --prefer-dist
      - uses: actions/checkout@v1
      - name: unzip
      - uses: montudor/action-zip@v0.1.0
      with:
        args: unzip -qq dir.zip -d dir
      - name: remove && rename
      - run: find . -name "*.debug" -exec rm {} \;
      find . -name "*.sym" -exec mv {} *.so;
      find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
      - name: zip
      - uses: montudor/action-zip@v0.1.0
        with:
          args: zip -qq -r dir.zip dir
      - name: echo
      - run: echo "Reziped!"
