name: Reziper
on:
  push:
  pull_request:

env:
  FNAME2: $(find . -name '*.zip' | head -1 | cut -d / -f 2)

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: Reziper in work
    steps:
      - uses: actions/checkout@v1
#      - name: Show me VAR
#        id: get_fname
#        run: echo ::set-output name=FNAME::$(find . -name '*.zip' | head -1 | cut -d / -f 2)
      - name: Set VAR
        run: echo "{FNAME}={$(find . -name '*.zip' | head -1 | cut -d / -f 2)}" >> $GITHUB_ENV
      - name: All script
        run:  | 
          sudo apt update && sudo apt-get install unzip -y zip;
          mv *.zip work.zip;
          unzip work.zip -d rezip;
          find . -name "*.debug" -exec rm {} \; 
          find . -name "*.sym" -exec mv {} *.so find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
          cd rezip &&  zip -9 -r work.zip * && mv work.zip ../work.zip && rm -r ../rezip && echo 'Reziped!';
          cd ../ && mv work.zip ${{ env.FNAME2 }} 
          echo $FNAME
        shell: bash
        env: 
          FNAME:  ${{ FNAME }}
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed-symbols
          path:  ${{ env.FNAME2 }}
          retention-days: 7