name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: sudo apt update
      - name: Install Unzip & zip
        run: sudo apt-get install unzip -y zip
      - name: Unzip
        run: unzip test.zip -d rezip;
      - name: remove && rename
        run: find . -name "*.debug" -exec rm {}; find . -name "*.sym" -exec mv {} *.so; find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
      - name: Zip
        run: cd rezip &&  zip -9 -r $1 * && mv $1 ../$1 && rm -r ../rezip;
      - name: echo
        run: echo "Reziped!"
