name: Reziper
on:
  push:
  pull_request:

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files
    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: sudo apt update
      - name: Install Unzip & zip
        run: sudo apt-get install unzip -y zip
      - name: Unzip
        run: unzip test.zip -d rezip;
      - name: Show me
        run: ls rezip || echo "No folder"
      - run: find . -name "*.debug" -exec rm {} \&& find . -name "*.sym" -exec mv {} *.so&& find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
      - run: cd rezip &&  zip -9 -r test.zip * && mv test.zip ../test.zip && rm -r ../rezip;
      - run: echo 'Reziped!'
        shell: bash
        env:
          ARCHIVE_NAME: test.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed-symbols
          path: test.zip
          retention-days: 7