name: Reziper
on:
  push:
  pull_request:

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files
    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: sudo apt update
      - name: Install Unzip & zip
        run: sudo apt-get install unzip -y zip
      - name: <any>.zip to work.zip
        run:  mv *.zip work.zip
      - name: Unzip
        run:  | 
          unzip work.zip -d rezip;
          find . -name "*.debug" -exec rm {} \; 
          find . -name "*.sym" -exec mv {} *.so find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
          cd rezip &&  zip -9 -r work.zip * && mv work.zip ../work.zip && rm -r ../rezip;
          echo 'Reziped!'
        shell: bash
        env:
          ARCHIVE_NAME: work.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed-symbols
          path: work.zip
          retention-days: 7