name: Reziper
on:
  push:
  pull_request:

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files
    steps:
    - name:  upd & install
      run: |
        sudo apt update && sudo apt-get install unzip -y zip;
        unzip $ARCHIVE_NAME -d rezip;
        find . -name "*.debug" -exec rm {} \;
        find . -name "*.sym" -exec mv {} *.so;
        find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
        cd rezip &&  zip -9 -r $1 * && mv $1 ../$1 && rm -r ../rezip;
        echo 'Reziped!'
      shell: bash
      env:
        ARCHIVE_NAME: test.zip
        
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: processed-symbols
        path: test.zip
        retention-days: 7
