name: Reziper
on:
  push:
  pull_request:

jobs:
  copy_files_job:
    runs-on: ubuntu-latest
    name: A job that copy files
    steps:
    - name:  upd & install
      run: sudo apt update && sudo apt-get install unzip -y zip
#    - run: test -f test.zip && echo '$FILE exists.' || mv *.zip test.zip
    - run: unzip test.zip -d rezip
    - run: find . -name "*.debug" -exec rm {} \&& find . -name "*.sym" -exec mv {} *.so&& find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
    - run: cd rezip &&  zip -9 -r test.zip * && mv test.zip ../test.zip && rm -r ../rezip;
    - run: echo 'Reziped!'
      shell: bash
      env:
        ARCHIVE_NAME: test.zip
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: processed-symbols
        path: test.zip
        retention-days: 7