name: Continuous Integration
on:
  push:
  pull_request:
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Update
        run: sudo apt update
      - name: Var test
        run: var1="test.zap"
      - name: Install Unzip & zip
        run: sudo apt-get install unzip -y zip
      - name: Unzip
        run: unzip test.zip -d rezip;
      - name: Show me
        run: ls rezip || echo "No folder"
      - run: find . -name "*.debug" -exec rm {} \;
      - run: find . -name "*.sym" -exec mv {} *.so;
      - run: find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
      - name: Zip
        run: cd rezip &&  zip -9 -r test.zip * && mv test.zip ../test.zip && rm -r ../rezip;
      - name: echo
        run: echo "Reziped!"
      - name: echo test
        run: echo $var1
