name: Reziper
on:
  push:
  pull_request:
jobs:
  composer-install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: run reziper.sh
        run: sh reziper.sh $ARCHIVE_NAME
        env:
          ARCHIVE_NAME: test.zip
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: processed-symbols
          path: $ARCHIVE_NAME
          retention-days: 7