name: Reziper
description: 'Ok. description.'
on:
  push:
  pull_request:
inputs:
  destinationFolder:  # path
    description: 'description 2'
    required: true
    default: '~'
outputs:
  copied-files: 
    description: "description 3"
    value: ${{ steps.random-number-generator.outputs.filesNo }}
jobs:
  runs-on: "ubuntu-latest"
  steps: 
    - name:  upd & install
      run: sudo apt update && sudo apt-get install unzip -y zip
    - run: unzip $1 -d rezip
    - run: find . -name "*.debug" -exec rm {} \
    - run: find . -name "*.sym" -exec mv {} *.so; find . -name '*.sym' -exec sh -c 'mv "$0" "${0%.sym}.so"' {} \;
    - run: cd rezip &&  zip -9 -r $1 * && mv $1 ../$1 && rm -r ../rezip;
    - run: echo 'Reziped!'
      shell: bash
      env:
        ARCHIVE_NAME: test.zip
    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: processed-symbols
        path: test.zip
        retention-days: 7